version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
      - service2

  service1:
    image: node:18
    container_name: service1
    working_dir: /app
    volumes:
      - ./service1:/app
    command: ["node", "server.js"]
    ports:
      - "3001:3001"

  service2:
    image: node:18
    container_name: service2
    working_dir: /app
    volumes:
      - ./service2:/app
    command: ["node", "server.js"]
    ports:
      - "3002:3002"
